######################################################################
# Automatically generated by qmake (3.1) Thu Jun 15 22:55:01 2017
######################################################################

TEMPLATE = app
TARGET = mocr
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h
SOURCES += MainWindow.cpp main.cpp
